server:
  port: 8089
  servlet:
    context-path: /api
spring:

  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-71-69-66.compute-1.amazonaws.com:5432/de3hb9kbna34m5
    username: hrnuetczxyznxb
    password: f47b3775628af864c5e4cb430ee61ac49ed01e4c65e2a523963d9dbcc99fe5ff